moodle:
  image: 'local/moodle:latest'
  restart: always
  hostname: 'moodle'
  ports:
    - '30080:80'
    - '30443:443'
    - '30022:22'
  volumes:
    - '/docker_volumes/srv/moodle/data:/var/www/moodledata'
    - '/docker_volumes/srv/moodle/app:/var/www/html/moodle'
  external_links:
    - mariadb_mariadb_1:db
